J = range(3)
I = range(2)

rule all:
    input:
        expand("output/result_{i}.txt", i=I)

rule sum:
    input:
        # dynamic rule, the value i is the current value for that job
        lambda wildcards: expand("input/data{I}_{J}.txt", I=wildcards.i, J=J)
    output:
        "output/result_{i}.txt"
    run:
        total = 0
        for f in input:
            with open(f) as fh:
                for line in fh.readlines():
                    total += int(line)
        with open(output[0], 'w') as fo:
            fo.write(str(total))
